import { StudyDocument, QuizConfig, Question, QuizResultReport, DashboardStats, WeakConceptItem, RecentActivityItem } from "@/types";

export const mockDashboardStats: DashboardStats = {
  totalDocuments: 6,
  totalQuestionsGenerated: 148,
  totalQuizzesTaken: 18,
  averageAccuracy: 82,
  totalStudyMinutes: 215,
  masteredConceptsCount: 24,
  weakConceptsCount: 3,
  questionsAttempted: 132,
  questionsGoal: 160,
};

export const mockWeakConcepts: WeakConceptItem[] = [
  {
    id: "weak-1",
    name: "Trees (AVL & Red-Black Rotations)",
    category: "Data Structures",
    accuracyPercentage: 42,
    questionsAttempted: 12,
    status: "critical",
    lastPracticed: "Yesterday",
    recommendedCount: 5,
  },
  {
    id: "weak-2",
    name: "Recursion & Call Stack Space",
    category: "Algorithms",
    accuracyPercentage: 55,
    questionsAttempted: 16,
    status: "moderate",
    lastPracticed: "2 days ago",
    recommendedCount: 5,
  },
  {
    id: "weak-3",
    name: "Graphs (Topological Sort & Cycles)",
    category: "Data Structures",
    accuracyPercentage: 68,
    questionsAttempted: 15,
    status: "moderate",
    lastPracticed: "3 days ago",
    recommendedCount: 4,
  },
  {
    id: "weak-4",
    name: "Proton Gradient & ATP Synthase",
    category: "Cellular Biology",
    accuracyPercentage: 50,
    questionsAttempted: 8,
    status: "critical",
    lastPracticed: "4 days ago",
    recommendedCount: 3,
  },
];

export const mockRecentActivities: RecentActivityItem[] = [
  {
    id: "act-1",
    title: "Trees & Binary Search Trees Quiz",
    documentTitle: "Data_Structures_and_Algorithms_Ch5.pdf",
    topics: ["Binary Search Trees", "AVL Trees", "Tree Traversals"],
    difficulty: "intermediate",
    score: 4,
    totalQuestions: 10,
    accuracyPercentage: 40,
    completedAt: "2026-09-14T18:40:00Z",
    durationSeconds: 380,
  },
  {
    id: "act-2",
    title: "Cellular Respiration & Chemiosmosis",
    documentTitle: "cell_biology_ch4_genetics.pdf",
    topics: ["Oxidative Phosphorylation", "Glycolysis", "ATP Synthase"],
    difficulty: "intermediate",
    score: 8,
    totalQuestions: 10,
    accuracyPercentage: 80,
    completedAt: "2026-09-14T14:15:00Z",
    durationSeconds: 420,
  },
  {
    id: "act-3",
    title: "Deep Learning Fundamentals & Backprop",
    documentTitle: "deep_learning_intro_cs480.pdf",
    topics: ["Loss Functions", "Chain Rule", "Activation Functions"],
    difficulty: "advanced",
    score: 9,
    totalQuestions: 10,
    accuracyPercentage: 90,
    completedAt: "2026-09-13T10:30:00Z",
    durationSeconds: 510,
  },
  {
    id: "act-4",
    title: "Microeconomics Market Elasticity",
    documentTitle: "econ_101_markets_elasticity.pdf",
    topics: ["Price Elasticity", "Consumer Surplus", "Supply Shifts"],
    difficulty: "easy",
    score: 5,
    totalQuestions: 5,
    accuracyPercentage: 100,
    completedAt: "2026-09-12T16:20:00Z",
    durationSeconds: 190,
  },
];


export const mockStudyDocuments: StudyDocument[] = [
  {
    id: "doc-1",
    title: "Cell Biology & Molecular Genetics",
    fileName: "cell_biology_ch4_genetics.pdf",
    fileSizeFormatted: "2.4 MB",
    pageCount: 28,
    wordCount: 14200,
    uploadedAt: "2026-09-12T14:30:00Z",
    summary: "Comprehensive guide covering eukaryotic cellular structures, organelle functions, ATP synthesis in mitochondria, DNA transcription/translation mechanisms, and Mendelian inheritance patterns.",
    quizzesTaken: 5,
    averageScore: 82,
    status: "ready",
    tags: ["Biology", "Genetics", "Cell Structure"],
    topics: [
      {
        id: "top-1",
        name: "Cell Organelles & Membrane Transport",
        description: "Endoplasmic reticulum, Golgi apparatus, lysosomal pathways, and active vs passive transport.",
        estimatedQuestions: 15,
        keyTerms: ["Phospholipid bilayer", "Endocytosis", "Osmosis", "Ribosomes"],
      },
      {
        id: "top-2",
        name: "Cellular Respiration & ATP Synthesis",
        description: "Glycolysis, Krebs cycle, and the electron transport chain inside the mitochondrial matrix.",
        estimatedQuestions: 12,
        keyTerms: ["Oxidative phosphorylation", "ATP synthase", "NADH", "Pyruvate"],
      },
      {
        id: "top-3",
        name: "DNA Replication & Protein Synthesis",
        description: "Helicase, DNA polymerase III, transcription into mRNA, and tRNA ribosome translation.",
        estimatedQuestions: 18,
        keyTerms: ["Codons", "RNA polymerase", "Okazaki fragments", "Anticodon"],
      },
      {
        id: "top-4",
        name: "Mendelian Genetics & Punnett Squares",
        description: "Dominant vs recessive alleles, law of segregation, and independent assortment.",
        estimatedQuestions: 10,
        keyTerms: ["Genotype", "Phenotype", "Heterozygous", "Allele"],
      },
    ],
  },
  {
    id: "doc-2",
    title: "Foundations of Neural Networks & Deep Learning",
    fileName: "deep_learning_intro_cs480.pdf",
    fileSizeFormatted: "4.1 MB",
    pageCount: 42,
    wordCount: 22800,
    uploadedAt: "2026-09-14T09:15:00Z",
    summary: "Core mathematical foundations of feedforward neural networks, backpropagation calculus, activation functions (ReLU, GELU, Softmax), gradient descent optimization, and regularization strategies.",
    quizzesTaken: 4,
    averageScore: 71,
    status: "ready",
    tags: ["Computer Science", "AI", "Mathematics"],
    topics: [
      {
        id: "top-5",
        name: "Perceptrons & Activation Functions",
        description: "Linear classification, sigmoid saturation, vanishing gradient, and ReLU properties.",
        estimatedQuestions: 14,
        keyTerms: ["Weights", "Bias", "Activation", "Linear Separability"],
      },
      {
        id: "top-6",
        name: "Backpropagation & Chain Rule",
        description: "Loss gradient propagation across layers and weight delta calculation.",
        estimatedQuestions: 16,
        keyTerms: ["Partial derivatives", "Loss surface", "Chain rule", "Jacobian"],
      },
      {
        id: "top-7",
        name: "Optimization Algorithms (SGD, Adam)",
        description: "Momentum, adaptive learning rates, RMSprop, and mini-batch dynamics.",
        estimatedQuestions: 12,
        keyTerms: ["Learning rate", "Momentum", "Adam optimizer", "Epochs"],
      },
    ],
  },
  {
    id: "doc-3",
    title: "Microeconomics: Market Equilibrium & Elasticity",
    fileName: "econ_101_markets_elasticity.pdf",
    fileSizeFormatted: "1.8 MB",
    pageCount: 19,
    wordCount: 9400,
    uploadedAt: "2026-09-10T16:00:00Z",
    summary: "Exploration of supply and demand curves, price elasticity of demand and supply, consumer/producer surplus, market shortages and surpluses, and price ceilings/floors.",
    quizzesTaken: 3,
    averageScore: 84,
    status: "ready",
    tags: ["Economics", "Finance", "Microeconomics"],
    topics: [
      {
        id: "top-8",
        name: "Law of Demand & Supply Equilibrium",
        description: "Shift factors vs movements along curves and market clearing price.",
        estimatedQuestions: 10,
        keyTerms: ["Equilibrium price", "Shortage", "Surplus", "Substitutes"],
      },
      {
        id: "top-9",
        name: "Price Elasticity of Demand (PED)",
        description: "Inelastic vs elastic goods, midpoint formula, and total revenue test.",
        estimatedQuestions: 12,
        keyTerms: ["Cross-price elasticity", "Income elasticity", "Unitary"],
      },
    ],
  },
];

export const mockQuestions: Question[] = [
  {
    id: "q-1",
    topic: "Cellular Respiration & ATP Synthesis",
    difficulty: "intermediate",
    type: "mcq",
    question: "During oxidative phosphorylation in the mitochondria, where does the highest concentration of hydrogen ions (protons) accumulate to drive ATP synthase?",
    options: [
      { id: "opt-a", text: "Inside the mitochondrial matrix" },
      { id: "opt-b", text: "Within the intermembrane space" },
      { id: "opt-c", text: "Attached to the outer membrane surface" },
      { id: "opt-d", text: "Inside the nuclear envelope" },
    ],
    correctAnswerIds: ["opt-b"],
    explanation: "Protons are actively pumped from the mitochondrial matrix into the intermembrane space by complexes I, III, and IV of the electron transport chain, creating an electrochemical gradient.",
    sourceQuote: "The electron transport chain pumps protons across the inner mitochondrial membrane into the intermembrane space, generating the proton-motive force that channels through ATP synthase (Section 4.3, p. 14).",
    conceptTested: "Proton Gradient & ATP Synthase Mechanism",
    pageReference: 14,
  },
  {
    id: "q-2",
    topic: "Cell Organelles & Membrane Transport",
    difficulty: "easy",
    type: "mcq",
    question: "Which organelle is primarily responsible for packaging and modifying proteins received from the rough endoplasmic reticulum before shipment?",
    options: [
      { id: "opt-a", text: "Lysosome" },
      { id: "opt-b", text: "Golgi apparatus" },
      { id: "opt-c", text: "Peroxisome" },
      { id: "opt-d", text: "Centrosome" },
    ],
    correctAnswerIds: ["opt-b"],
    explanation: "The Golgi apparatus modifies, sorts, and packages proteins into vesicles for secretion or delivery to other organelles.",
    sourceQuote: "Vesicles budding from the rough ER fuse with the cis face of the Golgi apparatus, where protein oligosaccharides are trimmed and tagged for targeting (Section 4.1, p. 6).",
    conceptTested: "Golgi Function in Secretory Pathway",
    pageReference: 6,
  },
  {
    id: "q-3",
    topic: "DNA Replication & Protein Synthesis",
    difficulty: "advanced",
    type: "mcq",
    question: "Why are Okazaki fragments synthesized exclusively on the lagging strand during DNA replication?",
    options: [
      { id: "opt-a", text: "DNA helicase only unzips DNA in the 3' to 5' direction" },
      { id: "opt-b", text: "DNA polymerase III can only add nucleotides in the 5' to 3' direction" },
      { id: "opt-c", text: "RNA primase is unable to bind to the leading strand template" },
      { id: "opt-d", text: "Topoisomerase prevents continuous synthesis on both strands" },
    ],
    correctAnswerIds: ["opt-b"],
    explanation: "Because DNA polymerase III can only synthesize in the 5' to 3' direction, the antiparallel lagging strand must be synthesized discontinuously away from the replication fork.",
    sourceQuote: "Since DNA polymerases can only elongate from the 3' hydroxyl end, the lagging strand template running 5' to 3' relative to fork progression must be copied in discontinuous segments termed Okazaki fragments (Section 4.4, p. 21).",
    conceptTested: "Lagging Strand Directionality & Okazaki Fragments",
    pageReference: 21,
  },
  {
    id: "q-4",
    topic: "Cellular Respiration & ATP Synthesis",
    difficulty: "intermediate",
    type: "mcq",
    question: "What is the primary terminal electron acceptor in the mitochondrial electron transport chain?",
    options: [
      { id: "opt-a", text: "NAD+" },
      { id: "opt-b", text: "Molecular Oxygen (O₂)" },
      { id: "opt-c", text: "Pyruvate" },
      { id: "opt-d", text: "Cytochrome c" },
    ],
    correctAnswerIds: ["opt-b"],
    explanation: "Molecular oxygen acts as the final electron acceptor in Complex IV, combining with protons to form water.",
    sourceQuote: "At complex IV, electrons are transferred to molecular oxygen (O₂), which binds free protons to yield water (H₂O) as a metabolic byproduct (Section 4.3, p. 15).",
    conceptTested: "Terminal Electron Acceptors",
    pageReference: 15,
  },
  {
    id: "q-5",
    topic: "Mendelian Genetics & Punnett Squares",
    difficulty: "easy",
    type: "mcq",
    question: "In a monohybrid cross between two heterozygous individuals (Bb x Bb) where 'B' is dominant for brown eyes and 'b' is recessive for blue eyes, what is the expected phenotypic ratio of brown to blue eyes in the offspring?",
    options: [
      { id: "opt-a", text: "1:1" },
      { id: "opt-b", text: "3:1" },
      { id: "opt-c", text: "9:3:3:1" },
      { id: "opt-d", text: "2:2:1" },
    ],
    correctAnswerIds: ["opt-b"],
    explanation: "A Bb x Bb cross yields BB (1), Bb (2), and bb (1). Both BB and Bb express the dominant brown phenotype, yielding a 3:1 phenotypic ratio.",
    sourceQuote: "Crossing two heterozygous carriers results in a 1:2:1 genotypic distribution and a characteristic 3:1 dominant-to-recessive phenotype split (Section 4.5, p. 25).",
    conceptTested: "Monohybrid Cross Phenotypic Ratios",
    pageReference: 25,
  },
];

export const mockQuizConfig: QuizConfig = {
  documentId: "doc-1",
  documentTitle: "Cell Biology & Molecular Genetics",
  selectedTopics: [
    "Cellular Respiration & ATP Synthesis",
    "DNA Replication & Protein Synthesis",
    "Cell Organelles & Membrane Transport",
    "Mendelian Genetics & Punnett Squares",
  ],
  difficulty: "intermediate",
  questionCount: 5,
  questionTypes: ["mcq"],
  timeLimitMinutes: 10,
};

export const mockQuizResult: QuizResultReport = {
  id: "result-8492",
  quizConfig: mockQuizConfig,
  completedAt: "2026-09-15T09:00:00Z",
  totalQuestions: 5,
  correctCount: 4,
  scorePercentage: 80,
  totalTimeSpentSeconds: 245,
  weakTopics: ["Cellular Respiration & ATP Synthesis"],
  hasRemediationAvailable: true,
  conceptMastery: [
    {
      concept: "Cell Organelles & Secretory Pathway",
      totalQuestions: 1,
      correctQuestions: 1,
      masteryPercentage: 100,
      status: "mastered",
      recommendation: "Strong foundational recall on organelle roles.",
    },
    {
      concept: "DNA Replication & Directionality",
      totalQuestions: 1,
      correctQuestions: 1,
      masteryPercentage: 100,
      status: "mastered",
      recommendation: "Excellent grasp of 5' to 3' enzymatic synthesis rules.",
    },
    {
      concept: "Mendelian Genetics",
      totalQuestions: 1,
      correctQuestions: 1,
      masteryPercentage: 100,
      status: "mastered",
      recommendation: "Accurate calculation of monohybrid crosses.",
    },
    {
      concept: "Proton Gradient & ATP Synthase",
      totalQuestions: 2,
      correctQuestions: 1,
      masteryPercentage: 50,
      status: "needs_review",
      recommendation: "Review the spatial orientation of the mitochondrial intermembrane space vs matrix during chemiosmosis.",
    },
  ],
  gradedQuestions: [
    {
      question: mockQuestions[0],
      userAnswer: {
        questionId: "q-1",
        selectedOptionIds: ["opt-a"], // Answered wrong on purpose for demo
        timeSpentSeconds: 45,
      },
      isCorrect: false,
      score: 0,
      feedback: "You selected 'Inside the mitochondrial matrix', but protons are pumped OUT of the matrix into the intermembrane space.",
      misconceptionIdentified: "Reversed direction of the proton electrochemical gradient in chemiosmosis.",
    },
    {
      question: mockQuestions[1],
      userAnswer: {
        questionId: "q-2",
        selectedOptionIds: ["opt-b"],
        timeSpentSeconds: 22,
      },
      isCorrect: true,
      score: 1,
      feedback: "Correct! The Golgi apparatus serves as the molecular sorting and packaging hub.",
    },
    {
      question: mockQuestions[2],
      userAnswer: {
        questionId: "q-3",
        selectedOptionIds: ["opt-b"],
        timeSpentSeconds: 65,
      },
      isCorrect: true,
      score: 1,
      feedback: "Correct! The unidirectional 5' to 3' restriction forces discontinuous lagging strand synthesis.",
    },
    {
      question: mockQuestions[3],
      userAnswer: {
        questionId: "q-4",
        selectedOptionIds: ["opt-b"],
        timeSpentSeconds: 30,
      },
      isCorrect: true,
      score: 1,
      feedback: "Correct! Oxygen is the final electron acceptor reduced to water.",
    },
    {
      question: mockQuestions[4],
      userAnswer: {
        questionId: "q-5",
        selectedOptionIds: ["opt-b"],
        timeSpentSeconds: 35,
      },
      isCorrect: true,
      score: 1,
      feedback: "Correct! 3:1 phenotypic ratio corresponds to 1 BB, 2 Bb (brown) vs 1 bb (blue).",
    },
  ],
};
